project:
  type: website

format:
  html:
    theme: 
      - cosmo
      - custom.scss
  
website:
  title: "Macroexpand 2025"
  description: "Clojure online conferences by Scicloj"
  site-url: "https://scicloj.github.io/macroexpand-2025"
  open-graph: true
  favicon: "images/sci-cloj-logo-transparent.png"
  image: "images/sci-cloj-logo-transparent.png"
  navbar:
    logo: "images/sci-cloj-logo-transparent.svg"
    search: true
    right:
    - {href: index.qmd, text: Home}
    - {href: speakers.qmd, text: Speakers}
    - {href: macroexpand_noj.qmd, text: "Macroexpand-Noj"}
    - {href: macroexpand_deep.qmd, text: "Macroexpand-Deep"}
